### ISSUE TITLE
error 1114

### ISSUE THREAD

**Issue by ragette0** [ari-zah/gaiasky#76]
> Gaia sky failed to work with this error message on Windows 10
> 
> "LoadLibrary failed with error 1114: A Dynamic Link Library (DLL) 
> initialization routine failed"

Anyone have this and been able to fix it?

**Comment by langurmonkey** [comment]
Is that all it says? This is not a Gaia Sky log.
A quick search on [Google](https://www.google.de/search?q=LoadLibrary+failed+with+error+1114%3A+A+Dynamic+Link+Library+(DLL)+initialization+routine+failed&oq=LoadLibrary+failed+with+error+1114%3A+A+Dynamic+Link+Library+(DLL)+initialization+routine+failed&aqs=chrome..69i57.246j0j7&sourceid=chrome&ie=UTF-8) seems to yield lots of results for that exact same error so it may or may not be related directly to Gaia Sky.
For instance, [here](https://steamcommunity.com/app/396890/discussions/0/458604254445517420/) is a thread in an unrelated product on Steam which contains a video with a solution to the error.
Let me know if you could fix this.

**Comment by ragette0** [comment]
Thanks, sorry for making you do the legwork for me, I should have googled it myself. I’m very anxious to use this. I have been a fan of Digital Universe for years.

**Comment by ragette0** [comment]
I’ll try it when I get home tonight.
Thanks again

**Comment by ragette0** [comment]
The video on the steam thread worked. (In power options just maximize graphic performance)
Thank you
________________________________

**Comment by langurmonkey** [comment]
Great!
I'm closing the issue then.
