### ISSUE TITLE
Crash - Vector pool null pointer when multithreading is on

### ISSUE THREAD

**Issue by langurmonkey** [ari-zah/gaiasky#83]
[Original message](https://aur.archlinux.org/packages/gaiasky/) from [8472](https://aur.archlinux.org/account/8472)

The app. hangs up (always) after a while (it's random, sometime it takes longer, sometime right), but obviously with the very same "Exception in thread "LWJGL Application" java.lang.NullPointerException" failure:
{
java -Xms1g -Xmx2g -XX:+UseConcMarkSweepGC -cp "/opt/gaiasky/lib/*" gaia.cu9.ari.gaiaorbit.desktop.GaiaSkyDesktop
GlobalConf - GUI scale factor set to 0.96946806
Loaded 1 music files
Configuration saved to ~/.gaiasky/global.properties
Display mode set to 1600x1200, fullscreen: false
FOV: 0.89079
19:22:25: GaiaSky - GLSL version: 4.50 NVIDIA
...
...
...
Exception in thread "LWJGL Application" java.lang.NullPointerException
at gaia.cu9.ari.gaiaorbit.util.coord.Coordinates.cartesianToSpherical(Coordinates.java:401)
at gaia.cu9.ari.gaiaorbit.scenegraph.CameraManager.updatePointerRADEC(CameraManager.java:220)
at gaia.cu9.ari.gaiaorbit.scenegraph.CameraManager.update(CameraManager.java:207)
at gaia.cu9.ari.gaiaorbit.GaiaSky.update(GaiaSky.java:468)
at gaia.cu9.ari.gaiaorbit.GaiaSky.render(GaiaSky.java:396)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:223)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
}

I'm running:
{
Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (Intel Skylake)
RAM: 16GB
GeForce GTX 750

x86_64
4.4.22-1-lts

jre8-openjdk 8.u102-1
}

**Comment by dv8472** [comment]
@langurmonkey:
> Can you outline what more or less in what situation the crash occurs?

Have just started the app., twice, and let it be running on the background, while I was opening this URL in order to reply back to you, when it hanged. On it's own, no input of mine was required.
At first attempt, it took longer until the freeze issue happened.
At second attempt, it hanged up almost immediately (when I was writing this text) after the app. got loaded with the default earth view.

> Is it completely random?

Looks like yes.


> What is the camera mode?

Default, the one from the app. start "Camera focus changed to Earth".

> I created a new issue in github for this here: https://github.com/ari-zah/gaiasky/issues/83

thx

**Comment by langurmonkey** [comment]
I think I have pinpointed the problem. This only happens when multithread (which is still experimental and produces worse results in my tests than the single-threaded version anyway) is enabled because of a non-threadsafe function. This will be fixed in the next release. As a workaround, can you disable multithreading and report back whether the problem is fixed?

**Comment by dv8472** [comment]
Yeah, that seems to be it.
After disabling the multithread, it's much better now.
Thx.
